version: '3.5'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: WhatsIn
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./data:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        networks:
            - whatsin

networks:
    whatsin:
        name: whatsin
        driver: bridge