version: '3.1'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: WhatsIn
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        networks:
            - whatsin

networks:
    whatsin:
        driver: bridge